#!/usr/bin/env node
/**
 * Reads .env.local or .env and writes extension/generated-env.js with
 * DDD_EXTENSION_API_KEY, INGEST_BASE_URL, DDD_DEBUG for the extension build.
 * Run before loading the extension or running npm run pack.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ENV_LOCAL = path.join(ROOT, ".env.local");
const ENV = path.join(ROOT, ".env");
const OUT = path.join(ROOT, "extension", "generated-env.js");

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, "utf8");
  const out = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1).replace(/\\"/g, '"');
    if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1).replace(/\\'/g, "'");
    out[key] = value;
  }
  return out;
}

const envLocal = parseEnvFile(ENV_LOCAL);
const env = parseEnvFile(ENV);
const vars = { ...env, ...envLocal };

const apiKey = vars.DDD_EXTENSION_API_KEY != null ? String(vars.DDD_EXTENSION_API_KEY).trim() : "";
const baseUrl = (vars.DDD_INGEST_BASE_URL != null ? String(vars.DDD_INGEST_BASE_URL).trim() : "") || "https://dailydispodeals.com";
const debug = /^(1|true|yes)$/i.test(String(vars.DEBUG || vars.DDD_DEBUG || "").trim());

const js = `// Generated by scripts/inject-env.js – do not edit by hand.
// Contains DDD_EXTENSION_API_KEY – ensure this file is in .gitignore.
const DDD_EXTENSION_API_KEY = ${JSON.stringify(apiKey)};
const INGEST_BASE_URL = ${JSON.stringify(baseUrl)};
const DDD_DEBUG = ${debug};
`;

fs.writeFileSync(OUT, js, "utf8");
if (!apiKey) {
  console.warn("[inject-env] DDD_EXTENSION_API_KEY is empty – ingest requests may be rejected.");
}
console.log("[inject-env] Wrote extension/generated-env.js (INGEST_BASE_URL=" + baseUrl + ", DDD_DEBUG=" + debug + ")");
